#version 460


#include "src/shaders/constants.glsl"
#include "src/shaders/compute/structs.glsl"
#include "src/shaders/compute/bindings.glsl"


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main() {
    /* PLACEHOLDER CODE */

    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(computeStorageImage);
    if (p.x >= size.x || p.y >= size.y) return;

    vec2 uv = (vec2(p) + 0.5) / vec2(size);
    imageStore(computeStorageImage, p, textureLod(envMap, uv, 0.0));
}
