#version 460


#include "src/shaders/constants.glsl"
#include "src/shaders/compute/structs.glsl"
#include "src/shaders/compute/bindings.glsl"
#include "src/shaders/compute/util.glsl"


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


CameraRay GenerateCameraRay(ivec2 pixelCoords, ivec2 imageSize) {
    float tanHalfFov = tan(camera.fov * 0.5);

    // Pixel center -> UV [0,1] -> NDC [-1,1]
    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(imageSize);
    vec2 ndc = uv * 2.0 - 1.0;
    ndc.y = -ndc.y; // Vulkan's y-axis convention is flipped (downwards is positive)
    // Account for aspect ratio
    ndc.x *= float(imageSize.x) / float(imageSize.y);

    CameraRay cameraRay;
    cameraRay.dir = normalize(
        camera.front +
        camera.right * (ndc.x * tanHalfFov) +
        camera.up * (ndc.y * tanHalfFov)
    );

    return cameraRay;
}

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageSize = imageSize(computeStorageImage);
    if (pixelCoords.x >= imageSize.x || pixelCoords.y >= imageSize.y) return;

    CameraRay cameraRay = GenerateCameraRay(pixelCoords, imageSize);
    cameraRay.dir = normalize(cameraRay.dir);
    vec3 envColor = SampleEquirectangular(envMap, cameraRay.dir);

    imageStore(computeStorageImage, pixelCoords, vec4(envColor, 1.0));
}
