site_name: Geodesix Documentation
site_url: https://github.com/normanhnchen/Geodesix

theme:
  name: material
  custom_dir: overrides
  features:
    navigation.footer: true

docs_dir: ../docs

nav:
- Home: index.md
- License: license.md
- Documentation:
  - Vulkan:
    - Vulkan/Overview.md
    - Vulkan/Resource_Acquisition_Is_Initialization.md
    - Vulkan/The_Vulkan_Instance.md
    - Vulkan/Validation_Layers.md
    - Vulkan/The_Physical_Device.md
    - Vulkan/Queues.md
    - Vulkan/The_Logical_Device.md
    - Vulkan/Window_Surface.md
    - Vulkan/The_Swap_Chain.md
    - Vulkan/Image_Views.md
    - Vulkan/Pipelines.md
    - Vulkan/Shaders.md
    - Vulkan/Fixed-Functions.md
    - Vulkan/Dynamic_States.md
    - Vulkan/Commands.md
